#!/usr/bin/env python3
"""Build Map of Content JSON for the graph visualization.

Reads transcripts/index.json (nodes) and each {id}.references.json
(edges via related_posts[].slug_pt). Writes docs/data/moc.json and
injects an inline JSON-LD block into docs/moc.html so AI crawlers can
read the graph without executing JavaScript.
"""
import json
import os
import re

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_PATH = os.path.join(PROJECT_DIR, "transcripts", "index.json")
OUT_DIR = os.path.join(PROJECT_DIR, "docs", "data")
OUT_PATH = os.path.join(OUT_DIR, "moc.json")
MOC_HTML = os.path.join(PROJECT_DIR, "docs", "moc.html")
INDEX_HTML_PT = os.path.join(PROJECT_DIR, "docs", "index.html")
INDEX_HTML_EN = os.path.join(PROJECT_DIR, "docs", "en", "index.html")

SITE_BASE = "https://adhenawer.net"

LD_BEGIN = "<!-- MOC-LD:BEGIN (auto-generated by scripts/build_moc.py) -->"
LD_END = "<!-- MOC-LD:END -->"

# Cards visible on the index pages whose HTML exists but has no entry in
# transcripts/index.json yet. Mirrors the ORPHAN_TAGS in docs/js/tags.js — keep
# them in sync until the orphans are properly indexed.
ORPHAN_TAGS = {
    "dario-amodei-scaling-rl-agi-futuro-anthropic": (["ia-2026", "agentic-engineering"], "core"),
    "dario-amodei-scaling-rl-agi-future-anthropic": (["ia-2026", "agentic-engineering"], "core"),
    "ronycoder-video": (["soft-skills", "carreira"], "core"),
    "ronycoder-arte-comunicar": (["soft-skills", "carreira"], "core"),
    "how-speak-patrick-winston-giving-talks-matter": (["soft-skills", "carreira"], "core"),
    "art-communicate-ronycoder": (["soft-skills", "carreira"], "core"),
}


def _short_title(title: str, subtitle: str) -> str:
    t = (title or "").strip()
    if ":" in t and len(t) > 42:
        t = t.split(":", 1)[0].strip()
    if " — " in t and len(t) > 42:
        t = t.split(" — ", 1)[0].strip()
    if len(t) > 48:
        t = t[:46].rstrip() + "…"
    return t


def _build_payload(index):
    nodes = []
    slug_set = set()
    for entry in index:
        slug = entry["slug"]
        if slug in slug_set:
            continue
        slug_set.add(slug)
        full_title = entry.get("title", slug)
        nodes.append({
            "id": slug,
            "title": _short_title(full_title, entry.get("subtitle", "")),
            "title_full": full_title,
            "subtitle": entry.get("subtitle", ""),
            "url_pt": f"posts/pt_br/{slug}.html",
            "url_en": f"posts/original/{entry.get('slug_en', slug)}.html",
            "tags": list(entry.get("tags") or []),
            "category": entry.get("category", "core"),
            "refs_total": (entry.get("references") or {}).get("total", 0),
        })

    edge_seen = set()
    edges = []
    for entry in index:
        slug = entry["slug"]
        refs_info = entry.get("references") or {}
        refs_path = refs_info.get("path")
        if not refs_path:
            continue
        abs_refs = os.path.join(PROJECT_DIR, refs_path)
        if not os.path.exists(abs_refs):
            continue
        with open(abs_refs) as f:
            refs = json.load(f)
        for rel in refs.get("related_posts") or []:
            target = rel.get("slug_pt")
            if not target or target == slug or target not in slug_set:
                continue
            key = tuple(sorted([slug, target]))
            if key in edge_seen:
                continue
            edge_seen.add(key)
            edges.append({"source": key[0], "target": key[1]})

    return {"nodes": nodes, "edges": edges}


def _build_jsonld_graph(payload):
    """Schema.org Dataset wrapping the MOC graph for crawlers."""
    nodes = payload["nodes"]
    edges = payload["edges"]
    parts = []
    parts.append({
        "@type": "Dataset",
        "@id": f"{SITE_BASE}/moc.html#dataset",
        "name": "Mapa de Conteúdo — adhenawer.net",
        "description": (
            "Grafo de artigos sobre Claude Code, engenharia agêntica, carreira "
            "em IA e produto. Cada nó é um post; arestas são related_posts."
        ),
        "url": f"{SITE_BASE}/moc.html",
        "creator": {"@type": "Person", "name": "adhenawer"},
        "keywords": sorted({t for n in nodes for t in n.get("tags") or []}),
        "size": f"{len(nodes)} posts, {len(edges)} edges",
    })
    for n in nodes:
        parts.append({
            "@type": "Article",
            "@id": f"{SITE_BASE}/{n['url_pt']}#node",
            "headline": n.get("title_full") or n["title"],
            "url": f"{SITE_BASE}/{n['url_pt']}",
            "inLanguage": "pt-BR",
            "keywords": n.get("tags") or [],
            "isPartOf": {"@id": f"{SITE_BASE}/moc.html#dataset"},
            "additionalType": "MapOfContentNode",
            "identifier": n["id"],
        })
    for e in edges:
        parts.append({
            "@type": "Action",
            "actionStatus": "https://schema.org/CompletedActionStatus",
            "additionalType": "MapOfContentEdge",
            "object": {"@id": f"{SITE_BASE}/posts/pt_br/{e['source']}.html#node"},
            "target": {"@id": f"{SITE_BASE}/posts/pt_br/{e['target']}.html#node"},
        })
    return {
        "@context": "https://schema.org",
        "@graph": parts,
    }


def _annotate_cards(html_path, payload):
    """Add data-tags + data-category attributes to each <a class="card">.

    This makes tags visible to crawlers / browsers without JS. The runtime
    tags.js still injects the visual pills, but the underlying metadata is
    already in the static HTML (graceful degradation, also helps SEO).

    Idempotent — strips any existing data-tags/data-category before re-adding.
    """
    if not os.path.exists(html_path):
        return False
    with open(html_path) as f:
        html = f.read()

    # Build slug -> attrs map (PT and EN slugs both)
    by_slug = {}
    for n in payload["nodes"]:
        attrs = (
            f'data-tags="{" ".join(n.get("tags") or [])}" '
            f'data-category="{n.get("category", "core")}"'
        )
        for url in (n.get("url_pt") or "", n.get("url_en") or ""):
            slug = _slug_from_href(url)
            if slug:
                by_slug[slug] = attrs

    for slug, (tags, category) in ORPHAN_TAGS.items():
        by_slug[slug] = f'data-tags="{" ".join(tags)}" data-category="{category}"'

    card_pattern = re.compile(
        r'(<a\s+[^>]*class="card"[^>]*?href="[^"]*?/([^/"]+)\.html"[^>]*?)(\s*>)',
        re.S,
    )
    strip_pattern = re.compile(r'\s+data-(?:tags|category)="[^"]*"')

    changed = [0]

    def replace(m):
        head, slug, tail = m.group(1), m.group(2), m.group(3)
        attrs = by_slug.get(slug)
        head_clean = strip_pattern.sub("", head)
        if not attrs:
            new = head_clean + tail
        else:
            new = head_clean + " " + attrs + tail
        if new != m.group(0):
            changed[0] += 1
        return new

    new_html = card_pattern.sub(replace, html)
    if new_html != html:
        with open(html_path, "w") as f:
            f.write(new_html)
        return changed[0]
    return 0


def _slug_from_href(href: str) -> str:
    m = re.search(r"/?([^/]+)\.html$", href or "")
    return m.group(1) if m else ""


def _inject_jsonld(html_path, payload):
    if not os.path.exists(html_path):
        return False
    with open(html_path) as f:
        html = f.read()

    jsonld = json.dumps(
        _build_jsonld_graph(payload),
        ensure_ascii=False,
        separators=(",", ":"),
    )
    block = (
        f"{LD_BEGIN}\n"
        f'<script type="application/ld+json">{jsonld}</script>\n'
        f"{LD_END}"
    )

    pattern = re.compile(re.escape(LD_BEGIN) + r".*?" + re.escape(LD_END), re.S)
    if pattern.search(html):
        new_html = pattern.sub(block, html)
    else:
        new_html = html.replace("</head>", block + "\n</head>", 1)

    if new_html != html:
        with open(html_path, "w") as f:
            f.write(new_html)
        return True
    return False


def main() -> None:
    with open(INDEX_PATH) as f:
        index = json.load(f)

    payload = _build_payload(index)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    n_nodes = len(payload["nodes"])
    n_edges = len(payload["edges"])
    print(f"moc.json: {n_nodes} nodes, {n_edges} edges → {OUT_PATH}")

    for path in (MOC_HTML, INDEX_HTML_PT, INDEX_HTML_EN):
        if _inject_jsonld(path, payload):
            print(f"injected JSON-LD → {os.path.relpath(path, PROJECT_DIR)}")

    for path in (INDEX_HTML_PT, INDEX_HTML_EN):
        n_changed = _annotate_cards(path, payload)
        if n_changed:
            print(f"annotated {n_changed} cards → {os.path.relpath(path, PROJECT_DIR)}")


if __name__ == "__main__":
    main()
