#!/usr/bin/env python3
"""Build Map of Content JSON for the graph visualization.

Reads transcripts/index.json (nodes) and each {id}.references.json
(edges via related_posts[].slug_pt). Writes docs/data/moc.json and
injects an inline JSON-LD block into docs/moc.html so AI crawlers can
read the graph without executing JavaScript.
"""
import json
import os
import re

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX_PATH = os.path.join(PROJECT_DIR, "transcripts", "index.json")
OUT_DIR = os.path.join(PROJECT_DIR, "docs", "data")
OUT_PATH = os.path.join(OUT_DIR, "moc.json")
MOC_HTML = os.path.join(PROJECT_DIR, "docs", "moc.html")
INDEX_HTML_PT = os.path.join(PROJECT_DIR, "docs", "index.html")
INDEX_HTML_EN = os.path.join(PROJECT_DIR, "docs", "en", "index.html")

SITE_BASE = "https://adhenawer.net"

LD_BEGIN = "<!-- MOC-LD:BEGIN (auto-generated by scripts/build_moc.py) -->"
LD_END = "<!-- MOC-LD:END -->"


def _short_title(title: str, subtitle: str) -> str:
    t = (title or "").strip()
    if ":" in t and len(t) > 42:
        t = t.split(":", 1)[0].strip()
    if " — " in t and len(t) > 42:
        t = t.split(" — ", 1)[0].strip()
    if len(t) > 48:
        t = t[:46].rstrip() + "…"
    return t


def _build_payload(index):
    nodes = []
    slug_set = set()
    for entry in index:
        slug = entry["slug"]
        if slug in slug_set:
            continue
        slug_set.add(slug)
        nodes.append({
            "id": slug,
            "title": _short_title(entry.get("title", slug), entry.get("subtitle", "")),
            "subtitle": entry.get("subtitle", ""),
            "url_pt": f"posts/pt_br/{slug}.html",
            "url_en": f"posts/original/{entry.get('slug_en', slug)}.html",
            "tags": list(entry.get("tags") or []),
            "category": entry.get("category", "core"),
            "refs_total": (entry.get("references") or {}).get("total", 0),
        })

    edge_seen = set()
    edges = []
    for entry in index:
        slug = entry["slug"]
        refs_info = entry.get("references") or {}
        refs_path = refs_info.get("path")
        if not refs_path:
            continue
        abs_refs = os.path.join(PROJECT_DIR, refs_path)
        if not os.path.exists(abs_refs):
            continue
        with open(abs_refs) as f:
            refs = json.load(f)
        for rel in refs.get("related_posts") or []:
            target = rel.get("slug_pt")
            if not target or target == slug or target not in slug_set:
                continue
            key = tuple(sorted([slug, target]))
            if key in edge_seen:
                continue
            edge_seen.add(key)
            edges.append({"source": key[0], "target": key[1]})

    return {"nodes": nodes, "edges": edges}


def _build_jsonld_graph(payload):
    """Schema.org Dataset wrapping the MOC graph for crawlers."""
    nodes = payload["nodes"]
    edges = payload["edges"]
    parts = []
    parts.append({
        "@type": "Dataset",
        "@id": f"{SITE_BASE}/moc.html#dataset",
        "name": "Mapa de Conteúdo — adhenawer.net",
        "description": (
            "Grafo de artigos sobre Claude Code, engenharia agêntica, carreira "
            "em IA e produto. Cada nó é um post; arestas são related_posts."
        ),
        "url": f"{SITE_BASE}/moc.html",
        "creator": {"@type": "Person", "name": "adhenawer"},
        "keywords": sorted({t for n in nodes for t in n.get("tags") or []}),
        "size": f"{len(nodes)} posts, {len(edges)} edges",
    })
    for n in nodes:
        parts.append({
            "@type": "Article",
            "@id": f"{SITE_BASE}/{n['url_pt']}#node",
            "headline": n["title"],
            "url": f"{SITE_BASE}/{n['url_pt']}",
            "inLanguage": "pt-BR",
            "keywords": n.get("tags") or [],
            "isPartOf": {"@id": f"{SITE_BASE}/moc.html#dataset"},
            "additionalType": "MapOfContentNode",
            "identifier": n["id"],
        })
    for e in edges:
        parts.append({
            "@type": "Action",
            "actionStatus": "https://schema.org/CompletedActionStatus",
            "additionalType": "MapOfContentEdge",
            "object": {"@id": f"{SITE_BASE}/posts/pt_br/{e['source']}.html#node"},
            "target": {"@id": f"{SITE_BASE}/posts/pt_br/{e['target']}.html#node"},
        })
    return {
        "@context": "https://schema.org",
        "@graph": parts,
    }


def _inject_jsonld(html_path, payload):
    if not os.path.exists(html_path):
        return False
    with open(html_path) as f:
        html = f.read()

    jsonld = json.dumps(
        _build_jsonld_graph(payload),
        ensure_ascii=False,
        separators=(",", ":"),
    )
    block = (
        f"{LD_BEGIN}\n"
        f'<script type="application/ld+json">{jsonld}</script>\n'
        f"{LD_END}"
    )

    pattern = re.compile(re.escape(LD_BEGIN) + r".*?" + re.escape(LD_END), re.S)
    if pattern.search(html):
        new_html = pattern.sub(block, html)
    else:
        new_html = html.replace("</head>", block + "\n</head>", 1)

    if new_html != html:
        with open(html_path, "w") as f:
            f.write(new_html)
        return True
    return False


def main() -> None:
    with open(INDEX_PATH) as f:
        index = json.load(f)

    payload = _build_payload(index)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    n_nodes = len(payload["nodes"])
    n_edges = len(payload["edges"])
    print(f"moc.json: {n_nodes} nodes, {n_edges} edges → {OUT_PATH}")

    for path in (MOC_HTML, INDEX_HTML_PT, INDEX_HTML_EN):
        if _inject_jsonld(path, payload):
            print(f"injected JSON-LD → {os.path.relpath(path, PROJECT_DIR)}")


if __name__ == "__main__":
    main()
